### ISSUE TITLE
Use lightweight stdlib tools where possible

### ISSUE THREAD

**Issue by rufuspollock** [otruja/sdg-indicators#1]
Is it possible to do the cleaning using simple python libs (and python3) e.g. urllib.urlretrieve and e.g. xlrd. pandas is heavy duty for such simple processing?

**Comment by otruja** [comment]
Yes. Fixed the script to use only standard libs `urllib` and `csv`, with the 3rd party `xlrd`.

**Comment by otruja** [comment]
FIXED
