### ISSUE TITLE
datapackage.json has windows style paths

### ISSUE THREAD

**Issue by rufuspollock** [otruja/sdg-indicators#2]
`archive\\sdg-indicators.xlsx` rather than

`archive/sdg-indicators.xlsx`

**Comment by otruja** [comment]
I've used the CLI `data` tool from Datahub to generate 'datapackage.json', so if it generates invalid file Who should I address this issue then?

**Comment by zelima** [comment]
@otruja let's open issue for that here https://github.com/datahq/datahub-qa/issues

**Comment by otruja** [comment]
@zelima Just opened a new issue.

**Comment by otruja** [comment]
FIXED then

**Comment by otruja** [comment]
FIXED
