### ISSUE TITLE
Resources list should only be clean data and other issues

### ISSUE THREAD

**Issue by rufuspollock** [otruja/sdg-indicators#3]
* [x] We don't usually include the archive file in the resource list (but i would include a sources property with the original source file ...)
* [x] the scripts should definitely not be in the datapackage.json
* [x] csv file has windows encoding not utf-8
* [x] No descriptions for columns in csv file
* [x] readme is not usually include in datapackage.json (if you have README.md) (it will get out of sync)
* [x] I don't think license info is correct. This is just a dataset and i doubt they are asserting rights. Whilst we can't say this for certain i would indicate this i would also make clear that the compiler of the dataset (us) are licensing our work under PDDL.
* [x] I don't know why we have pathType in the datapackage.json

**Comment by otruja** [comment]
So to avoid most of these issues, I mainly should put in a folder only the final .csv file. Then do `data init` via CLI, and then add scripts, archive, and readme.md. Is that correct?

Also, the following is unclear to me - `include a sources property with the original source file`.

Other issues are should be fixed by now. Please review.

**Comment by zelima** [comment]
@otruja You can do that way as well or run `data init` with `-i` (interactive) flag. `data init -i` will ask you before adding any file to the datapackage. 

Source property would look something like this: `{source: https://some-website.com/path/to/the/otiginal/file.csv}`

Generally, datasets look much better, great work! Maybe a small improvement for it:
* Intro is a bit big to me. I would move all that part in the `data` section and leave the short description of the dataset, you can come up by yourself
* `preparation` part still says you need panadas to run it. 
  * include exact command of how to run the script Eg: `python scripts/process.py`
